name: Feature request
description: Suggest something
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do
      description: The problem, rather than a proposed solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would help
